package stu.edu.jack.entity;

public class RecordInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.recordid
     *
     * @mbggenerated
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.recordname
     *
     * @mbggenerated
     */
    private String recordname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.intime
     *
     * @mbggenerated
     */
    private String intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.outtime
     *
     * @mbggenerated
     */
    private String outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.inway
     *
     * @mbggenerated
     */
    private String inway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.changedept
     *
     * @mbggenerated
     */
    private String changedept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.discontent
     *
     * @mbggenerated
     */
    private String discontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.medicontent
     *
     * @mbggenerated
     */
    private String medicontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.doctorid
     *
     * @mbggenerated
     */
    private String doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_info.checkid
     *
     * @mbggenerated
     */
    private String checkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.recordid
     *
     * @return the value of record_info.recordid
     *
     * @mbggenerated
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.recordid
     *
     * @param recordid the value for record_info.recordid
     *
     * @mbggenerated
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.recordname
     *
     * @return the value of record_info.recordname
     *
     * @mbggenerated
     */
    public String getRecordname() {
        return recordname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.recordname
     *
     * @param recordname the value for record_info.recordname
     *
     * @mbggenerated
     */
    public void setRecordname(String recordname) {
        this.recordname = recordname == null ? null : recordname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.intime
     *
     * @return the value of record_info.intime
     *
     * @mbggenerated
     */
    public String getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.intime
     *
     * @param intime the value for record_info.intime
     *
     * @mbggenerated
     */
    public void setIntime(String intime) {
        this.intime = intime == null ? null : intime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.outtime
     *
     * @return the value of record_info.outtime
     *
     * @mbggenerated
     */
    public String getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.outtime
     *
     * @param outtime the value for record_info.outtime
     *
     * @mbggenerated
     */
    public void setOuttime(String outtime) {
        this.outtime = outtime == null ? null : outtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.inway
     *
     * @return the value of record_info.inway
     *
     * @mbggenerated
     */
    public String getInway() {
        return inway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.inway
     *
     * @param inway the value for record_info.inway
     *
     * @mbggenerated
     */
    public void setInway(String inway) {
        this.inway = inway == null ? null : inway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.hospital
     *
     * @return the value of record_info.hospital
     *
     * @mbggenerated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.hospital
     *
     * @param hospital the value for record_info.hospital
     *
     * @mbggenerated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.department
     *
     * @return the value of record_info.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.department
     *
     * @param department the value for record_info.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.changedept
     *
     * @return the value of record_info.changedept
     *
     * @mbggenerated
     */
    public String getChangedept() {
        return changedept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.changedept
     *
     * @param changedept the value for record_info.changedept
     *
     * @mbggenerated
     */
    public void setChangedept(String changedept) {
        this.changedept = changedept == null ? null : changedept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.discontent
     *
     * @return the value of record_info.discontent
     *
     * @mbggenerated
     */
    public String getDiscontent() {
        return discontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.discontent
     *
     * @param discontent the value for record_info.discontent
     *
     * @mbggenerated
     */
    public void setDiscontent(String discontent) {
        this.discontent = discontent == null ? null : discontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.medicontent
     *
     * @return the value of record_info.medicontent
     *
     * @mbggenerated
     */
    public String getMedicontent() {
        return medicontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.medicontent
     *
     * @param medicontent the value for record_info.medicontent
     *
     * @mbggenerated
     */
    public void setMedicontent(String medicontent) {
        this.medicontent = medicontent == null ? null : medicontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.doctorid
     *
     * @return the value of record_info.doctorid
     *
     * @mbggenerated
     */
    public String getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.doctorid
     *
     * @param doctorid the value for record_info.doctorid
     *
     * @mbggenerated
     */
    public void setDoctorid(String doctorid) {
        this.doctorid = doctorid == null ? null : doctorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.userid
     *
     * @return the value of record_info.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.userid
     *
     * @param userid the value for record_info.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_info.checkid
     *
     * @return the value of record_info.checkid
     *
     * @mbggenerated
     */
    public String getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_info.checkid
     *
     * @param checkid the value for record_info.checkid
     *
     * @mbggenerated
     */
    public void setCheckid(String checkid) {
        this.checkid = checkid == null ? null : checkid.trim();
    }
}